php bin/console app:create-season 'preseason-1' 'Preseason 1' 0
php bin/console app:create-season '1' 'Season 1' 1
php bin/console app:register-payment '1' 'Giglio'
php bin/console app:register-payment '1' 'Obelix'
php bin/console app:register-payment '1' 'Lanzjan'
php bin/console app:register-payment '1' 'Il-Karm'
php bin/console app:register-payment '1' 'Evilbeys'
php bin/console app:register-payment '1' 'Derius'
php bin/console app:register-payment '1' 'Rizzler'
php bin/console app:register-payment '1' 'Steve'
php bin/console app:register-payment '1' 'Southboy15'
php bin/console app:register-payment '1' 'Tristan'
php bin/console app:register-payment '1' 'Markulegend'
php bin/console app:register-payment '1' 'BladerZ'
php bin/console app:register-payment '1' 'Otrebor'
php bin/console app:register-payment '1' 'Guzman93'
php bin/console app:import-tournament 'Gamebreaker 20-06' '2026-06-20' '/app/var/data/imports/2026-06-20-gamebreaker-20-06.txt' --season='preseason-1' --challonge='https://worldbeyblade.challonge.com/co5nncw8' --knockout='L-Anzjan'
php bin/console app:import-tournament 'Gamesplus BX Only 21-06' '2026-06-21' '/app/var/data/imports/2026-06-21-gamesplus-bx-only-21-06.txt' --season='preseason-1' --challonge='https://challonge.com/vcxocrcg' --knockout='Markinu'
php bin/console app:import-tournament 'Gamebreaker CX Only 27-06' '2026-06-27' '/app/var/data/imports/2026-06-27-gamebreaker-cx-only-27-06.txt' --season='preseason-1' --challonge='https://challonge.com/wc0vkczl'
php bin/console app:import-tournament 'Gamesplus 28-06' '2026-06-28' '/app/var/data/imports/2026-06-28-gamesplus-28-06.txt' --season='preseason-1' --challonge='https://challonge.com/4luqbuv4'
php bin/console app:register-payment '1' 'Markinu'
php bin/console app:register-payment '1' 'Ripnburst'
php bin/console app:import-tournament 'Gamebreaker 04 July' '2026-07-04' '/app/var/data/imports/2026-07-04-gamebreaker-04-july.txt' --season='1' --challonge='https://challonge.com/8t3m15fl' --knockout='Mezz'
php bin/console app:register-payment '1' 'Danjel'
php bin/console app:register-payment '1' 'Myers'
php bin/console app:register-payment '1' 'Mezz'
php bin/console app:register-payment '1' 'Federico'
php bin/console app:register-payment '1' 'Butcher'
