php bin/console app:create-season 'preseason-1' 'Preseason 1' 0
php bin/console app:create-season '1' 'Season 1' 1
php bin/console app:register-payment '1' 'Giglio'
php bin/console app:register-payment '1' 'Obelix'
php bin/console app:register-payment '1' 'Lanzjan'
php bin/console app:register-payment '1' 'Il-Karm'
php bin/console app:register-payment '1' 'Evilbeys'
php bin/console app:register-payment '1' 'Derius'
php bin/console app:register-payment '1' 'Rizzler'
php bin/console app:register-payment '1' 'Steve'
php bin/console app:register-payment '1' 'Southboy15'
php bin/console app:register-payment '1' 'Tristan'
php bin/console app:register-payment '1' 'Markulegend'
php bin/console app:register-payment '1' 'BladerZ'
php bin/console app:register-payment '1' 'Otrebor'
php bin/console app:register-payment '1' 'Guzman93'
php bin/console app:import-tournament 'Gamebreaker 20-06' '2026-06-20' '/app/var/data/imports/2026-06-20-gamebreaker-20-06.txt' --season='preseason-1' --challonge='https://worldbeyblade.challonge.com/co5nncw8' --knockout='L-Anzjan'
php bin/console app:import-tournament 'Gamesplus BX Only 21-06' '2026-06-21' '/app/var/data/imports/2026-06-21-gamesplus-bx-only-21-06.txt' --season='preseason-1' --challonge='https://challonge.com/vcxocrcg' --knockout='Markinu'
php bin/console app:import-tournament 'Gamebreaker CX Only 27-06' '2026-06-27' '/app/var/data/imports/2026-06-27-gamebreaker-cx-only-27-06.txt' --season='preseason-1' --challonge='https://challonge.com/wc0vkczl'
php bin/console app:import-tournament 'Gamesplus 28-06' '2026-06-28' '/app/var/data/imports/2026-06-28-gamesplus-28-06.txt' --season='preseason-1' --challonge='https://challonge.com/4luqbuv4'
php bin/console app:register-payment '1' 'Markinu'
php bin/console app:register-payment '1' 'Ripnburst'
php bin/console app:import-tournament 'Gamebreaker 04 July' '2026-07-04' '/app/var/data/imports/2026-07-04-gamebreaker-04-july.txt' --season='1' --challonge='https://challonge.com/8t3m15fl' --knockout='Mezz'
php bin/console app:register-payment '1' 'Danjel'
php bin/console app:register-payment '1' 'Myers'
php bin/console app:register-payment '1' 'Mezz'
php bin/console app:register-payment '1' 'Federico'
php bin/console app:register-payment '1' 'Butcher'
php bin/console app:register-payment '1' 'Belti'
php bin/console app:import-tournament 'Gamesplus 05 July' '2026-07-05' '/app/var/data/imports/2026-07-05-gamesplus-05-july.txt' --season='1' --challonge='https://challonge.com/9yuqg2pi' --knockout='Evilbeys'
php bin/console app:register-payment '1' 'Fir3bladetv'
php bin/console app:register-payment '1' 'Amanda'
php bin/console app:import-tournament '11 July Gamebreaker 2v2 Player A' '2026-07-11' '/app/var/data/imports/2026-07-11-11-july-gamebreaker-2v2-player-a.txt' --season='1' --challonge='https://challonge.com/vi/uhxii7az'
php bin/console app:import-tournament '11 July Gamebreaker 2v2 Player B' '2026-07-11' '/app/var/data/imports/2026-07-11-11-july-gamebreaker-2v2-player-b.txt' --season='1' --challonge='https://challonge.com/vi/uhxii7az'
php bin/console app:import-tournament 'Gamesplus 12-07' '2026-07-12' '/app/var/data/imports/2026-07-12-gamesplus-12-07.txt' --season='1' --challonge='https://challonge.com/vi/zx9el0js' --knockout='Giglio'
php bin/console app:import-tournament 'Gamebreaker 18th July' '2026-07-18' '/app/var/data/imports/2026-07-18-gamebreaker-18th-july.txt' --season='1' --challonge='https://challonge.com/vi/cd0ljdsv' --knockout='Markinu'
php bin/console app:import-tournament '19th July Gamesplus 2v2 Player A' '2026-07-19' '/app/var/data/imports/2026-07-19-gamesplus-team-tournament-player-a-19th-july.txt' --season='1' --challonge='https://challonge.com/ivanixk6'
php bin/console app:import-tournament '19th July Gamesplus 2v2 Player B' '2026-07-19' '/app/var/data/imports/2026-07-19-19th-july-gamesplus-2v2-player-b.txt' --season='1' --challonge='https://challonge.com/ivanixk6'
php bin/console app:register-payment '1' 'Beastblade'
php bin/console app:import-tournament 'Gamebreaker 25-07' '2026-07-25' '/app/var/data/imports/2026-07-25-gamebreaker-25-07.txt' --season='1' --challonge='https://challonge.com/decysc7o' --knockout='Il-Karm'
php bin/console app:import-tournament 'Gamesplus 26-07' '2026-07-26' '/app/var/data/imports/2026-07-26-gamesplus-26-07.txt' --season='1' --challonge='https://challonge.com/6xaipmyd' --knockout='Obelix'
php bin/console app:import-tournament 'Gamebreaker 08-01' '2026-08-01' '/app/var/data/imports/2026-08-01-gamebreaker-08-01.txt' --season='1' --challonge='https://challonge.com/76x1a3jy' --knockout='Evilbeys'
php bin/console app:import-tournament 'Gamesplus 08-02' '2026-08-02' '/app/var/data/imports/2026-08-02-gamesplus-08-02.txt' --season='1' --challonge='https://challonge.com/wr7bqivn' --knockout='Rizzler'
php bin/console app:import-tournament 'Gamebreaker 08-08' '2026-08-08' '/app/var/data/imports/2026-08-08-gamebreaker-08-08.txt' --season='1' --challonge='https://challonge.com/mpcmoi5x' --knockout='Markinu'
php bin/console app:import-tournament 'Gamesplus 08-09' '2026-08-09' '/app/var/data/imports/2026-08-09-gamesplus-08-09.txt' --season='1' --challonge='https://challonge.com/6uwwkf2x' --knockout='Giglio'
php bin/console app:import-tournament 'Gamebreaker 15-08' '2026-08-15' '/app/var/data/imports/2026-08-15-gamebreaker-15-08.txt' --season='1' --challonge='https://challonge.com/6top55x2' --knockout='Rizzler'
php bin/console app:import-tournament 'Gamesplus 16-08' '2026-08-16' '/app/var/data/imports/2026-08-16-gamesplus-16-08.txt' --season='1' --challonge='https://challonge.com/nppk0890' --knockout='Guzman93'
