php bin/console app:create-season 'preseason-1' 'Preseason 1'
php bin/console app:create-season '1' 'Season 1'
php bin/console app:register-payment '1' 'Giglio'
php bin/console app:register-payment '1' 'Obelix'
php bin/console app:register-payment '1' 'L-Anzjan'
php bin/console app:register-payment '1' 'Il-Karm'
php bin/console app:register-payment '1' 'Evilbeys'
php bin/console app:register-payment '1' 'Derius'
php bin/console app:register-payment '1' 'Il-Butcher'
php bin/console app:register-payment '1' 'Rizzler'
php bin/console app:register-payment '1' 'Steve'
php bin/console app:register-payment '1' 'Southboy15'
php bin/console app:register-payment '1' 'Tristan'
php bin/console app:register-payment '1' 'Markulegend'
php bin/console app:register-payment '1' 'BladerZ'
php bin/console app:register-payment '1' 'Otrebor'
php bin/console app:register-payment '1' 'Guzman93'
php bin/console app:register-payment '1' 'Kaori'
php bin/console app:create-season 'preseason-1' 'Preseason 1'
php bin/console app:create-season '1' 'Season 1'
